### ISSUE TITLE
Linkedin Requires explicit scope setting.

### ISSUE THREAD

**Issue by jahagirdar** [b10m/p5-Dancer2-Plugin-Auth-OAuth#17]
See https://docs.microsoft.com/en-us/linkedin/shared/authentication/authorization-code-flow for details.
Linked in now requires explicit setting of a scope field as defined below
```
scope | URL-encoded, space-delimited list of member permissions your application is requesting on behalf of the user. These must be explicitly requested. For example,
 scope=r_liteprofile%20r_emailaddress%20w_member_social.
```

**Comment by Pero-Moretti** [comment]
What would be a good default for this? Since the scope could easily be set in the Dancer yml config, and given the large warning on Microsoft's web site saying "only request what you need", wouldn't it be better to leave this up to the implementer of the app to define what they should use?

plugins:
  Auth::OAuth:
    providers:
      Twitter:
        query_params:
          authorize:
            scope: (something here)
            response_type: 'code'

NB: At the moment you'd also need to include the response_type, because defining the "query_params" overwrites the config in the provider. However, I have a PR in to fix that, so this should be short-lived.

**Comment by Pero-Moretti** [comment]
Follow up; the latest version of Auth::OAuth now uses a hash merge for config options, so you no longer need to define everything under "query_params", only what you want changed from the default - in order words, you don't need the "response_type" key.
